FROM node:16

ARG PORT
ENV PORT=${PORT}

ARG TYPEORM_CONNECTION
ENV TYPEORM_CONNECTION=${TYPEORM_CONNECTION}

ARG TYPEORM_HOST
ENV TYPEORM_HOST=${TYPEORM_HOST}

ARG TYPEORM_USERNAME
ENV TYPEORM_USERNAME=${TYPEORM_USERNAME}

ARG TYPEORM_PASSWORD
ENV TYPEORM_PASSWORD=${TYPEORM_PASSWORD}

ARG TYPEORM_DATABASE
ENV TYPEORM_DATABASE=${TYPEORM_DATABASE}

ARG TYPEORM_PORT
ENV TYPEORM_PORT=${TYPEORM_PORT}

ARG TYPEORM_SYNCHRONIZE
ENV TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}

ARG JWT_SECRET
ENV JWT_SECRET=${JWT_SECRET}

ARG JWT_REFRESH_SECRET
ENV JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

WORKDIR /usr/app/backend
 
COPY . /usr/app/backend/

RUN npm install

RUN npm run build

CMD [ "npm", "start" ]